readium/r2-navigator-kotlin

- README.md
> repo move updates

- build.gradle
- r2-navigator/build.gradle
- r2-navigator/r2-navigator.iml
- r2-navigator/src/main/java/org/readium/r2/navigator/DRMManagementActivity.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/R2EpubActivity.kt
- r2-navigator/src/main/res/menu/menu_toc.xml
adding multi-flavor to support flavor specific dependencies
> gradle update for multiple flavors & code cleanup

- r2-navigator/src/main/res/values/strings.xml
fixes https://github.com/readium/r2-testapp-kotlin/issues/104
> Added potential right end string

- r2-navigator/src/main/java/org/readium/r2/navigator/R2EpubActivity.kt
…uced. this fixes the selection of the right resources.
> TOC selection on reflowable layout fixed

- r2-navigator/src/main/java/org/readium/r2/navigator/R2EpubActivity.kt
allowing for change of columns in FXL. using the same user settings as for reflowable column count. 1,2 or auto
auto we still need to implement but for now auto defaults to 1
> fxl change column count 

- r2-navigator/src/main/java/org/readium/r2/navigator/R2EpubActivity.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/UserSettings.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/fxl/R2FXLLayout.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/pager/R2BasicWebView.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/pager/R2EpubPageFragment.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/pager/R2FXLPageFragment.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/pager/R2FragmentPagerAdapter.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/pager/R2PagerAdapter.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/pager/R2ViewPager.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/pager/R2WebView.kt
- r2-navigator/src/main/res/layout/fxlview_double.xml
- r2-navigator/src/main/res/layout/fxlview_single.xml
primarily fixes https://github.com/readium/r2-testapp-kotlin/issues/121
one issue still remains and will be resolved in a separate PR, Swiping from the outer edge of the screen results in resource swipe
> Several Pager fixes and improvements

- r2-navigator/src/main/java/org/readium/r2/navigator/R2EpubActivity.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/pager/R2BasicWebView.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/pager/R2ViewPager.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/pager/R2WebView.kt
> Fixes/edge swipe #152

- r2-navigator/build.gradle
- r2-navigator/r2-navigator.iml
- r2-navigator/src/main/java/org/readium/r2/navigator/pager/R2FragmentPagerAdapter.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/pager/R2WebView.kt
Using Timber the TAG is not needed
> Fixed debug logging

- build.gradle
- r2-navigator/build.gradle
- r2-navigator/r2-navigator.iml
this will allow building between develop and master
> set r2 branch in build.gradle

- r2-navigator/src/main/java/org/readium/r2/navigator/R2EpubActivity.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/pager/R2ViewPager.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/pager/R2WebView.kt
Fixes #73 
Fixes https://github.com/readium/r2-testapp-kotlin/issues/188
Fixes https://github.com/readium/r2-testapp-kotlin/issues/203
all the above issue are the same issue basically.
> fixed touch events, no disabling needed anymore

- r2-navigator/src/main/java/org/readium/r2/navigator/R2CbzActivity.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/R2EpubActivity.kt
> added missing allowToggleActionBar check

- r2-navigator/build.gradle
- r2-navigator/src/main/assets/scripts/touchHandling.js
- r2-navigator/src/main/java/org/readium/r2/navigator/R2BasicWebView.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/R2WebView.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/cbz/R2CbzActivity.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/epub/R2EpubActivity.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/pager/R2ViewPager.kt
fixes https://github.com/readium/r2-testapp-kotlin/issues/214
> various swipe fixes

- r2-navigator/src/main/java/org/readium/r2/navigator/epub/R2EpubActivity.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/pager/R2EpubPageFragment.kt
fixes an issue where the current locator has the wrong fragment  handling after search (there might be more to be done)
> fixes current locator issue after search

- r2-navigator/src/main/java/org/readium/r2/navigator/IR2Activity.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/audiobook/R2AudiobookActivity.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/cbz/R2CbzActivity.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/epub/IR2Highlightable.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/epub/IR2Selectable.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/epub/R2EpubActivity.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/pager/R2EpubPageFragment.kt
- Fix broadcasting the `currentLocation`.
- Use the `Publication.positionList` for the `currentLocation`.
> Add the Publication's positionList

- r2-navigator/build.gradle
> Upgrade Appcompat

- r2-navigator/src/main/java/org/readium/r2/navigator/R2WebView.kt
prevent app crash when debuging webview.
> prevent app crash when debuging webview.

- r2-navigator/src/main/java/org/readium/r2/navigator/GlobalVars.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/epub/R2EpubActivity.kt
See https://github.com/readium/r2-testapp-kotlin/pull/306
> Fix broken server if a publication file contains special characters

- r2-navigator/src/main/java/org/readium/r2/navigator/audiobook/R2AudiobookActivity.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/cbz/R2CbzActivity.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/divina/R2DiViNaActivity.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/epub/R2EpubActivity.kt
See https://github.com/readium/r2-testapp-kotlin/issues/286
> Use the PublicationRepository to fix the TransactionTooLargeException

- r2-navigator/src/main/java/org/readium/r2/navigator/IR2Activity.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/NavigatorFragmentFactory.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/cbz/R2CbzActivity.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/epub/R2EpubActivity.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/extensions/Publication.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/pdf/PdfNavigatorFragment.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/pdf/R2PdfActivity.kt
A few changes to prepare the upcoming release:
* PDF and Fragment usages are marked as experimental
> Prepare release

- r2-navigator/src/main/assets/readium/divina/divinaTouchHandling.js
- r2-navigator/src/main/assets/readium/scripts/touchHandling.js
Fix https://github.com/readium/r2-navigator-kotlin/issues/137
> Fix video touch intercept

- r2-navigator/src/main/java/org/readium/r2/navigator/NavigatorFragmentFactory.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/R2BasicWebView.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/pager/R2EpubPageFragment.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/pager/R2FXLPageFragment.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/pager/R2PagerAdapter.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/pdf/PdfNavigatorFragment.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/pdf/R2PdfActivity.kt
- r2-navigator/src/main/res/layout/activity_r2_epub.xml
- r2-navigator/src/main/res/layout/viewpager_fragment_epub.xml
* Send EPUB's onTap on the UI thread
* Move the bookTitle view from the page fragment to the EPUB activity's layout
> Fragment fixes

- r2-navigator/src/main/java/org/readium/r2/navigator/R2WebView.kt
See https://github.com/readium/r2-navigator-kotlin/issues/146
See https://github.com/readium/r2-testapp-kotlin/issues/296
> fixes content offset issue

- CHANGELOG.md
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- r2-navigator/build.gradle
- r2-navigator/src/main/java/org/readium/r2/navigator/pager/R2EpubPageFragment.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/pdf/PdfNavigatorFragment.kt
> Upgrade Kotlin, Gradle and dependencies

- r2-navigator/src/main/assets/readium/scripts/highlight.js
- r2-navigator/src/main/java/org/readium/r2/navigator/epub/R2EpubActivity.kt
> Fix possible crash when selecting a highlight

- CHANGELOG.md
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- r2-navigator/build.gradle
- r2-navigator/src/main/java/org/readium/r2/navigator/R2BasicWebView.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/R2WebView.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/audiobook/R2AudiobookActivity.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/cbz/R2CbzActivity.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/divina/R2DiViNaActivity.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/epub/EpubNavigatorFragment.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/epub/R2EpubActivity.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/epub/fxl/R2FXLLayout.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/extensions/Locator.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/image/ImageNavigatorFragment.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/pager/R2FragmentPagerAdapter.kt
- r2-navigator/src/main/java/org/readium/r2/navigator/pager/R2PagerAdapter.kt
- Updated the Kotlin version
- Updated Gradle
- Updated dependencies
- Replaced deprecated code as best as possible.  There is still old code out there that can't be replaced easily
- Cleaned up warnings as best as possible. Several files/functions were annotated to ignore warnings because of the above point or because the functions themselves are marked as deprecated
> Kotlin and Gradle updates

- r2-navigator/src/main/java/org/readium/r2/navigator/epub/EpubNavigatorFragment.kt
- Add the title for the current location object for epubs, just as on the swift part.
> Add title in current location for epubs format
